version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

  product:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "30001:3001"
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

  order:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - "mongodb"
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "85:85"
    depends_on:
      - user
      - product
      - order

volumes:
  mongo-data: